# Makefile for Rust

check:
	cargo check

build:
	cargo build

format:
	cargo fmt

lint:
	cargo clippy

test:
	cargo test

clean:
	cargo clean

release:
	cargo build --release

all: check build format lint test