name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Rust_SQL

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check
        run: make check

      - name: Format
        run: make format

      - name: Test
        run: make test

      - name: Build Release Binary
        run: cargo build --release

      - name: List target directory
        run: ls -R target/

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-sql-binary
          path: Rust_SQL/target/release/Rust_SQL
          if-no-files-found: error